# Workflow name
name: 'Run `Vue Converter` tests'

# Event for the workflow
on:
  # push:
  pull_request:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./vue/

    # Job Steps
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Display NodeJS version
        run: node -v

      - name: Install dependencies, build and test
        run: |
          npm ci
          npm run build --if-present
          npm run test:unit
